# 서버포트 변경
# 프로퍼티 파일에서 지정
# server.port=8080
server:
  port: 8080

# 기본 에러페이지 사용하지 않겠다. 그러면 템플릿의 에러페이지가 실행된다.
# server.error.whitelabel.enabled=false
  error:
    whitelabel:
      enabled: false
      
# 자동 리로드
spring:
  devtools:
    livereload:
      enabled: true
# ---------------------------------------------------------------------
# H2 DB 설정
# ---------------------------------------------------------------------
  h2:
    console:
      enabled: true
      path: /h2
# ---------------------------------------------------------------------
# DataSource 설정
# ---------------------------------------------------------------------
  datasource:
    url: jdbc:h2:~/mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
## Database connection pooling properties
    tomcat.max-wait: 10000
    tomcat.max-active: 50
    tomcat.max-idle: 20
    tomcat.min-idle: 5
# ---------------------------------------------------------------------
# jpa 설정
# ---------------------------------------------------------------------
  jpa:
    hibernate:
      # ddl-auto: create  
      ddl-auto: update  
    database-platform: org.hibernate.dialect.H2Dialect
    show_sql: true
# ---------------------------------------------------------------------
# 로그 레벨 설정하기
# ---------------------------------------------------------------------
# 전체 로그 레벨 설정(기본 info)
# logging.level.root=debug
logging:
  level:
    root: info
# kr.top2blue.boot3 패키지와 그 하위 로그 레벨 설정
    kr:
      top2blue:
        jpa: debug
# ?에 어떤 값이 들어갔는지 확인하기        
    org:
      hibernate:
        type:
          descriptor:
            sql: trace    
# ---------------------------------------------------------------------

  