# 서버 포트 변경
server:
  port: 8080
# 기본 에러페이지 사용하지 않겠다. 그러면 템플릿의 에러페이지가 실행된다.
  error:
    whitelabel:
      enabled: false
      
# 자동 리로드
spring:
  devtools:
    livereload:
      enabled: true
#=============================================================
# 국제화 : INTERNATIONALIZATION (MessageSourceAutoConfiguration)
#-------------------------------------------------------------
  messages:
    basename: messages/message
    encoding: UTF-8
#=============================================================
# message
main:
  title: <b>Hello Spring Boot(application.yml)!!!</b>

# ---------------------------------------------------------------------
# 로그 레벨 설정하기
# 전체 로그 레벨 설정(기본 info)
# logging.level.root=debug
logging:
  level:
    root: info
# kr.top2blue.boot3 패키지와 그 하위 로그 레벨 설정
    kr.top2blue.boot3: debug
# ---------------------------------------------------------------------
